version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      API_PORT: 3000
      DB_URL: "mongodb://0.0.0.0:27017/test"
      REDIS_HOST: "localhost"
      REDIS_PORT: 6379
      REDIS_PASSWORD: "123456"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro